version: "3.2"

services:
  mongodb:
    image: mongo
    volumes:
      - "./db:/data/db"
  girder:
    build:
      context: ./devops/girder
    privileged: true
    command: -c "python3 /src/provision.py && girder mount /mnt/fuse && girder serve"
    ports:
      - "${GIRDER_PORT-8080}:8080"
    links:
      - mongodb
      - memcached
    volumes:
      - "./assetstore:/assetstore"
      - "./logs/girder:/root/.girder/logs"
  memcached:
    image: memcached
    # Set the item size to bigger than our uncompressed tiles and the memory
    # allocation to 4 Gb.
    command: -m 256 --max-item-size 8M
