services:
  girder:
    build:
      context: ./devops/girder
    privileged: true
    command: -c "python3 /src/provision.py && python3 /src/provision-prod.py && girder mount /mnt/fuse && girder serve"
    ports:
      - "${GIRDER_PORT-8080}:8080"
    links:
      - memcached
    volumes:
      # For some versions of Docker on OSX, adding delegated speeds up file
      # access.  It should do no harm on other systems.
      - "./logs/girder:/root/.girder/logs:delegated"
      - '/var/run/docker.sock:/var/run/docker.sock'
      # AWS Certificate to access DocumentDB
      - "/root/global-bundle.pem:/root/global-bundle.pem"
    env_file:
      - "./docker.env"
      - "./docker-prod.env"
    container_name: "girder"

  memcached:
    image: memcached
    # Set the item size to bigger than our uncompressed tiles and the memory
    # allocation to 4 Gb.
    command: -m 256 --max-item-size 8M
