version: "3.2"

services:
  mongodb:
    image: mongo
  # rabbitmq:
  #   image: rabbitmq
  girder:
    build:
      context: ./devops/girder
    command: "-d mongodb://mongodb:27017/girder --host 0.0.0.0"
    ports:
      - "${GIRDER_PORT-8080}:8080"
    links:
      - mongodb
      # - rabbitmq
    volumes:
      - "store:/store"
      - "./logs/girder:/root/.girder/logs"
  # girder-worker:
  #   build:
  #     context: ./devops/girder-worker
  #   environment:
  #     - "GIRDER_WORKER_BROKER=amqp://guest:guest@rabbitmq/"
  #   links:
  #     - mongodb
  #     - rabbitmq
  #     - girder
  #   volumes:
  #     - "store:/store:ro"
  #     - "./logs/girder-worker:/root/.girder/logs"

volumes:
  store: null
