version: "3.2"

services:
  mongodb:
    image: mongo
    volumes:
      - "./db:/data/db"
    ports:
      - "27017:27017"

  girder:
    build:
      context: ./devops/girder
    privileged: true
    command: -c "python3 /src/provision.py && girder mount /mnt/fuse && girder serve"
    ports:
      - "${GIRDER_PORT-8080}:8080"
    links:
      - mongodb
      - memcached
    volumes:
      # For some versions of Docker on OSX, adding delegated speeds up file
      # access.  It should do no harm on other systems.
      - "./assetstore:/assetstore:delegated"
      - "./logs/girder:/root/.girder/logs:delegated"
    env_file:
      - "./docker.env"
    depends_on:
      - "mongodb"
      - "broker"
    container_name: "girder"

  memcached:
    image: memcached
    # Set the item size to bigger than our uncompressed tiles and the memory
    # allocation to 4 Gb.
    command: -m 256 --max-item-size 8M

  broker:
    image: rabbitmq:3
    env_file: "./docker.env"

  worker:
    image: girder/girder_worker
    env_file:
      - "./docker.env"
    links:
      - girder
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - broker
    container_name: "worker"
    user: root
