version: "3.2"

services:
  mongodb:
    image: mongo
  girder:
    build:
      context: ./devops
    command: "-d mongodb://mongodb:27017/girder --host 0.0.0.0"
    ports:
      - "8080:8080"
    links:
      - mongodb
    volumes:
      - "store:/store"

volumes:
  store: null
