name: Compile WASM

on:
  push:
    paths:
      - itk/**
  pull_request:
    paths:
      - itk/**

jobs:
  all:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Compile with itk-wasm
        run: pnpm emscripten-build
