name: Compile WASM

on:
  push:
    paths:
      - itk/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm ci
      - name: Compile with itk-wasm
        run: npm run emscripten-build
